CREATE TABLE category (
    category_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    subject varchar NOT NULL,
    exam_type varchar NOT NULL,
    created_ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT category_pk PRIMARY KEY (category_id)
)

CREATE TABLE question_answers (
    question_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_id int NOT NULL,
    question varchar NOT NULL,
    answer varchar NOT NULL,
    created_ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT question_answers_pk PRIMARY KEY (question_id),
    CONSTRAINT question_answers_fk FOREIGN KEY (category_id) REFERENCES category(category_id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TYPE roles AS ENUM ('admin', 'user')
CREATE TABLE role (
    role_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name roles,
    CONSTRAINT role_pk PRIMARY KEY (role_id)
)

CREATE TABLE users (
    user_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    active BOOLEAN NOT NULL DEFAULT true,
    role_id INT NOT NULL,
    username varchar NOT NULL,
    password varchar NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (user_id),
    CONSTRAINT user_fk FOREIGN KEY (role_id) REFERENCES role(role_id) ON UPDATE CASCADE ON DELETE CASCADE
)